### ISSUE TITLE
Lost subscription

### ISSUE THREAD

**Issue by thejustsoul** [Hunter5000/Twitch-Alarm#9]
Constantly reset the subscription (" You aren't following any channels! "), I'm tired already to add them manually! And yet, why is there no field for entering multiple channels, not just one? Getting really annoying :(

**Comment by Hunter5000** [comment]
I've had this problem too. It may have something to do with the data in simple storage going over the maximum quota. I've attempted to fix this in version 1.8.6, so hopefully it goes away.

**Comment by thejustsoul** [comment]
Thanks, I hope the issue is resolved. 

And then I called this little bug is, if in a field where you need to enter the channel, press ENTER, then everything will disappear before re-entering the settings.

**Comment by Hunter5000** [comment]
I've noticed that before as well. Turns out the bug seems to be an internal JavaScript error with the HTML form tag. I've worked around that and fixed the bug in version 1.8.8, as well as allowing proper usage of the ENTER key to add followed channels and import followed channels from a Twitch user.

**Comment by thejustsoul** [comment]
Thanks for fix :) 
P.S. Will there be a possibility to import the list from a field (a few lines) or *.txt, as well as export the list to a file?

**Comment by Hunter5000** [comment]
I have actually planned this feature previously and already have localized text for it. However, I am not sure if I can export the list as a file.... I will take another look at it, and if I cannot do the exporting feature I will at least do the importing part.

Edit: 1.9.0 released... you can now import and export followed channels using .txt files! That was actually much easier than I thought it'd be. Play around with it and report any issues.

**Comment by thejustsoul** [comment]
Today again lost all subscription, version 1.10.2 (1.11.5 ?) :(
Upd: and all settings.

**Comment by Hunter5000** [comment]
I've lost my followed channels and settings as well even after my attempted fix, and after further examination, I don't think this has to do specifically with my add-on. The reason I don't think it has to do with my add-on in particular is because, whenever I lose my followed channels on this add-on, I also lose my settings on another add-on that I use. I think it may have to do with simple storage as an API, rather than a fault in my particular add-on.

Until a permanent solution can be found, try saving your followed channels with the new export feature so you can quickly import them back if you lose them.

As for your settings, I may create the ability to export them soon. It shouldn't be too big of a hassle to change them back though.

**Comment by thejustsoul** [comment]
I don't use too many extensions, but the settings are lost only in Twitch-Alarm (do not exclude that there is a conflict with some extension, for example I have an extension of "Self-Destructing Cookies", maybe it somehow affected. If Twitch-Alarm stores the settings in LocalStorage, it is cleared when the browser is closed this addon (but then why not every time after you close your browser lost these settings)..

Can change the storage settings at your extension? I'm not a master, but can be changed to the SQLITE3 database format (if that helps). 

Thank you for the opportunity to export and import the channel list. Your extension at the moment that is best for Firefox for monitoring the Twitch Streams :)

**Comment by Hunter5000** [comment]
This issue has not been brought up in a while and I think it is fixed. The issue seemed to be caused by the add-on creating massive memory leaks, leading to a browser crash. Following the crash, all settings would be lost, including followed channels.

However with these memory issues being (hopefully?) fixed, I think this issue is solved. Please let me know if anyone has experienced this issue after this post.

**Comment by thejustsoul** [comment]
For a long time is not lost settings, everything is in order :)

**Comment by Hunter5000** [comment]
Excellent, I think this issue is closed now.

**Comment by thejustsoul** [comment]
Again lost all subscriptions.
Just clicked on the extension icon, got a white window, no stream. Restarted the browser, all also white bed sheet, turned off/turned on the addon and all settings are gone.... "You aren't following any channels!"

Apparently after auto-update it all happened, I don't know.

**Comment by Hunter5000** [comment]
Very odd. Tell me if this happens again, because part of the reason may be
that the last update completely internally reworked how settings work. In
the meantime, you can alleviate this issue by making use of the new ability
to import and export settings to file. If this issue can be pinpointed to a
specific cause, however, then I will fix it as soon as possible.
